[package]
name = "normal2bump"
version = "0.1.0"
edition = "2021"

[dependencies]
image       = "^0.24"
rayon       = "^1.6"
wgpu        = "0.14"
anyhow      = "1.0.68"
pollster    = "0.2"
bytemuck    = {version="1.12", features=["derive"]}
